YAML_DIR = "/vagrant/confs"

SERVER_NAME = "mliS"
SERVER_IP = "192.168.56.110"
SERVER_SCRIPT = <<-SHELL
  export INSTALL_K3S_EXEC="--flannel-iface=eth1"
  export K3S_KUBECONFIG_MODE="644"
  sudo apt-get update -y
  sudo apt-get install -y curl
  curl -sfL https://get.k3s.io | sh -s -
  sleep 5
  kubectl apply -f #{YAML_DIR}
  SHELL

MEMORY = 2048
CPUS = 4

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/bullseye64/versions/11.20221219.1/providers/virtualbox.box"

  # Server
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell", inline: SERVER_SCRIPT
    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
  end
end
